handle ttl=0
node-cache-manager/node-cache-manager-redis-yet pull request #153
Opened 2023-01-30 14:54 UTC by ekmutai

- Fixes: ERR invalid expire time in set when ttl is set to 0
- Allow passing of ttl=0 to remove expiry

2023-01-31 03:59 UTC, botika commented
Please put test for this bug. Thanks!

2023-01-31 06:56 UTC, ekmutai commented
Done @botika

2023-01-31 14:58 UTC, botika requested changes

2023-01-31 14:58 UTC, botika commented on src/index.ts
> +      const t = ttl === undefined || ttl === 0 ? options?.ttl : ttl;
bad

2023-01-31 14:58 UTC, botika commented on test/index.test.ts
> +
uncompleted

2023-01-31 14:58 UTC, botika commented on test/index.test.ts
> +
uncompleted

2023-02-02 17:21 UTC, ekmutai commented
@botika please review and share any further feedback

2023-02-02 22:29 UTC, botika commented
Sorry, I did it. #156

2023-02-02 22:29 UTC, closed without merging